[package]
name = "raft"
version = "0.1.0"
authors = ["Jason Longshore <hello@jasonlongshore.com>"]
edition = "2018"

[dependencies]
pantomime = { path = "../../" }

[dev-dependencies]
pantomime = { path = "../../", features = ["testkit"] }

