[package]
name = "posix-signals"
version = "0.1.0"
authors = ["Jason Longshore <hello@jasonlongshore.com>"]
edition = "2018"

[dependencies]
pantomime = { path = "../../", features = ["posix-signals-support"] }
